name: Build for Windows

on:
  push:
    tags:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Add Toolchain
      run: rustup toolchain install stable-x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --verbose --target x86_64-pc-windows-gnu --release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/homeassistant_hotkeys.exe
